from core.callbacks.vocmapcallback import VOCEvalCheckpoint
from core.callbacks.cocomapcallback import COCOEvalCheckpoint
from core.callbacks.lrschedular import WarmUpScheduler, CosineAnnealingScheduler